import { ResourceSpec } from '../resource';

export const CONTENT: ResourceSpec = {
  name: 'content',
  describe: 'Storefront content — pages, blog, widgets, scripts',
  children: [
    {
      name: 'pages',
      describe: 'Storefront pages',
      path: 'content/pages',
      style: 'v3-item',
      idLabel: 'page',
      fields: ['id', 'name', 'type', 'is_visible', 'parent_id', 'sort_order', 'url'],
      params: ['channel_id', 'name', 'name:like', 'type', 'is_visible', 'parent_id'],
      ops: ['list', 'get', 'create', 'update', 'delete', 'delete-many'],
      actions: [
        {
          name: 'update-many',
          describe: 'Update pages in bulk',
          method: 'PUT',
          path: 'v3/content/pages',
          body: true,
          done: 'Pages updated',
        },
      ],
    },
    {
      name: 'pages-v2',
      describe: 'Storefront pages (legacy V2)',
      path: 'pages',
      style: 'v2-item',
      idLabel: 'page',
      fields: ['id', 'title', 'type', 'is_visible', 'parent_id', 'sort_order'],
    },
    {
      name: 'blog',
      describe: 'Blog posts and tags',
      children: [
        {
          name: 'posts',
          describe: 'Blog posts',
          path: 'blog/posts',
          style: 'v2-item',
          idLabel: 'blog post',
          ops: ['list', 'get', 'create', 'update', 'delete', 'delete-many'],
          fields: ['id', 'title', 'url', 'is_published', 'published_date', 'author'],
          actions: [
            {
              name: 'count',
              describe: 'Count blog posts',
              method: 'GET',
              path: 'v2/blog/posts/count',
              envelope: false,
            },
          ],
        },
        {
          name: 'tags',
          describe: 'Blog tags',
          path: 'blog/tags',
          style: 'v2-item',
          ops: ['list'],
          fields: ['tag', 'post_ids'],
        },
      ],
    },
    {
      name: 'scripts',
      describe: 'Storefront scripts',
      path: 'content/scripts',
      style: 'v3-item',
      idLabel: 'script',
      fields: ['uuid', 'name', 'description', 'location', 'visibility', 'kind', 'channel_id'],
      params: ['channel_id'],
    },
    {
      name: 'widgets',
      describe: 'Page Builder widgets',
      path: 'content/widgets',
      style: 'v3-item',
      idLabel: 'widget',
      fields: ['uuid', 'name', 'widget_template_uuid', 'channel_id', 'date_created'],
      params: ['widget_template_uuid', 'channel_id'],
    },
    {
      name: 'widget-templates',
      describe: 'Page Builder widget templates',
      path: 'content/widget-templates',
      style: 'v3-item',
      idLabel: 'widget template',
      fields: ['uuid', 'name', 'kind', 'channel_id', 'date_created'],
      params: ['channel_id', 'kind'],
      actions: [
        {
          name: 'preview',
          describe: 'Render a template against sample data',
          method: 'POST',
          path: 'v3/content/widget-templates/{uuid}/preview',
          args: ['uuid'],
          body: true,
        },
      ],
    },
    {
      name: 'placements',
      describe: 'Widget placements',
      path: 'content/placements',
      style: 'v3-item',
      idLabel: 'placement',
      fields: ['uuid', 'widget_uuid', 'template_file', 'region', 'status', 'channel_id'],
      params: ['channel_id', 'template_file', 'region', 'entity_id', 'status'],
    },
    {
      name: 'regions',
      describe: 'Regions a template exposes for placements',
      path: 'content/regions',
      style: 'v3-item',
      ops: ['list'],
      fields: ['name', 'id'],
      params: ['template_file', 'entity_id'],
    },
  ],
};

export const THEMES: ResourceSpec = {
  name: 'themes',
  describe: 'Storefront themes',
  path: 'themes',
  style: 'v3-item',
  idLabel: 'theme',
  ops: ['list', 'get', 'delete'],
  fields: ['uuid', 'name', 'is_private', 'is_active'],
  actions: [
    {
      name: 'upload',
      describe: 'Upload a theme .zip',
      method: 'POST',
      path: 'v3/themes',
      upload: { field: 'file' },
      done: 'Theme upload queued',
    },
    {
      name: 'activate',
      describe: 'Activate a theme variation',
      method: 'POST',
      path: 'v3/themes/actions/activate',
      body: true,
      done: 'Theme activated',
    },
    {
      name: 'download',
      describe: 'Request a download of a theme',
      method: 'POST',
      path: 'v3/themes/{uuid}/actions/download',
      args: ['uuid'],
      body: true,
    },
    {
      name: 'job',
      describe: 'Check a theme upload or download job',
      method: 'GET',
      path: 'v3/themes/jobs/{job_id}',
      args: ['job_id'],
    },
    {
      name: 'configurations',
      describe: 'List a theme’s saved configurations',
      method: 'GET',
      path: 'v3/themes/{uuid}/configurations',
      args: ['uuid'],
      params: ['channel_id', 'uuid:in', 'variation_uuid:in', 'type'],
    },
    {
      name: 'validate',
      describe: 'Validate a theme configuration',
      method: 'POST',
      path: 'v3/themes/{uuid}/configurations/validate',
      args: ['uuid'],
      body: true,
    },
    {
      name: 'custom-templates',
      describe: 'List custom templates in a theme version',
      method: 'GET',
      path: 'v3/themes/custom-templates/{version_uuid}',
      args: ['version_uuid'],
    },
  ],
};

export const MARKETING: ResourceSpec = {
  name: 'marketing',
  describe: 'Coupons, gift certificates, banners, and emails',
  children: [
    {
      name: 'coupons',
      describe: 'Coupons',
      path: 'coupons',
      style: 'v2-item',
      idLabel: 'coupon',
      // V2 exposes no single-coupon GET; filter the list instead.
      ops: ['list', 'create', 'update', 'delete', 'delete-many'],
      fields: ['id', 'name', 'type', 'amount', 'code', 'enabled', 'num_uses', 'expires'],
      params: ['code', 'name', 'type', 'min_id', 'max_id', 'exclude_type'],
      actions: [
        {
          name: 'count',
          describe: 'Count coupons',
          method: 'GET',
          path: 'v2/coupons/count',
          envelope: false,
        },
      ],
    },
    {
      name: 'gift-certificates',
      describe: 'Gift certificates',
      path: 'gift_certificates',
      style: 'v2-item',
      idLabel: 'gift certificate',
      ops: ['list', 'get', 'create', 'update', 'delete', 'delete-many'],
      fields: ['id', 'code', 'amount', 'balance', 'status', 'to_email', 'expiry_date'],
      params: ['code', 'order_id', 'min_id', 'max_id'],
    },
    {
      name: 'banners',
      describe: 'Storefront banners',
      path: 'banners',
      style: 'v2-item',
      idLabel: 'banner',
      ops: ['list', 'get', 'create', 'update', 'delete', 'delete-many'],
      fields: ['id', 'name', 'page', 'location', 'visible', 'date_type'],
      actions: [
        {
          name: 'count',
          describe: 'Count banners',
          method: 'GET',
          path: 'v2/banners/count',
          envelope: false,
        },
      ],
    },
    {
      name: 'email-templates',
      describe: 'Transactional email templates',
      path: 'marketing/email-templates',
      style: 'v3-item',
      idLabel: 'template',
      ops: ['list', 'get', 'update', 'delete'],
      fields: ['type_id', 'body', 'translations'],
      params: ['channel_id'],
    },
    {
      name: 'abandoned-cart-emails',
      describe: 'Abandoned cart emails',
      path: 'marketing/abandoned-cart-emails',
      style: 'v3-item',
      idLabel: 'abandoned cart email',
      fields: ['id', 'coupon_code', 'notify_at_minutes', 'template_id', 'is_active'],
      actions: [
        {
          name: 'default',
          describe: 'Get the default abandoned cart email',
          method: 'GET',
          path: 'v3/marketing/abandoned-cart-emails/default',
        },
      ],
      children: [
        {
          name: 'settings',
          describe: 'Abandoned cart email settings',
          path: 'marketing/abandoned-cart-emails/settings',
          style: 'v3-singleton',
        },
      ],
    },
  ],
};

export const STOREFRONT: ResourceSpec = {
  name: 'storefront',
  describe: 'Storefront tokens, redirects, and template associations',
  actions: [
    {
      name: 'token',
      describe: 'Mint a Storefront GraphQL API token',
      method: 'POST',
      path: 'v3/storefront/api-token',
      body: true,
    },
    {
      name: 'impersonation-token',
      describe: 'Mint a customer impersonation token',
      method: 'POST',
      path: 'v3/storefront/api-token-customer-impersonation',
      body: true,
    },
    {
      name: 'revoke-tokens',
      describe: 'Revoke every storefront token issued before a date',
      method: 'DELETE',
      path: 'v3/storefront/api-token',
      done: 'Storefront tokens revoked',
    },
  ],
  children: [
    {
      name: 'redirects',
      describe: '301 redirects',
      path: 'storefront/redirects',
      style: 'v3-batch',
      idLabel: 'redirect',
      ops: ['list', 'update', 'delete'],
      fields: ['id', 'from_path', 'site_id', 'to'],
      params: ['site_id', 'keyword', 'id:in', 'sort', 'include'],
      actions: [
        {
          name: 'jobs',
          describe: 'List import/export jobs',
          method: 'GET',
          path: 'v3/storefront/redirects/imex/jobs',
        },
        {
          name: 'export',
          describe: 'Start a redirect export',
          method: 'POST',
          path: 'v3/storefront/redirects/imex/export',
          body: true,
        },
        {
          name: 'import',
          describe: 'Start a redirect import',
          method: 'POST',
          path: 'v3/storefront/redirects/imex/import',
          body: true,
        },
        {
          name: 'export-events',
          describe: 'Poll an export job',
          method: 'GET',
          path: 'v3/storefront/redirects/imex/export/{uuid}/events',
          args: ['uuid'],
        },
        {
          name: 'import-events',
          describe: 'Poll an import job',
          method: 'GET',
          path: 'v3/storefront/redirects/imex/import/{uuid}/events',
          args: ['uuid'],
        },
        {
          name: 'download',
          describe: 'Download a finished export',
          method: 'GET',
          path: 'v3/storefront/redirects/imex/export/{uuid}/download',
          args: ['uuid'],
          download: true,
          done: 'Export downloaded',
        },
      ],
    },
    {
      name: 'redirects-v2',
      describe: '301 redirects (legacy V2)',
      path: 'redirects',
      style: 'v2-item',
      idLabel: 'redirect',
      ops: ['list', 'get', 'create', 'update', 'delete', 'delete-many'],
      fields: ['id', 'path', 'forward'],
      actions: [
        {
          name: 'count',
          describe: 'Count legacy redirects',
          method: 'GET',
          path: 'v2/redirects/count',
          envelope: false,
        },
      ],
    },
    {
      name: 'custom-template-associations',
      describe: 'Custom template assignments for products, categories, and pages',
      path: 'storefront/custom-template-associations',
      style: 'v3-batch',
      idLabel: 'association',
      ops: ['list', 'update', 'delete'],
      fields: ['id', 'channel_id', 'entity_id', 'file_name', 'type'],
      params: ['channel_id', 'entity_id:in', 'type', 'id:in'],
    },
  ],
};
