import { ResourceSpec } from '../resource';
import { metafields } from './metafields';

const ORDER_FIELDS = ['id', 'status', 'customer_id', 'date_created', 'total_inc_tax', 'currency_code', 'payment_method', 'items_total'];
const ORDER = 'orders/{order_id}';

export const ORDERS: ResourceSpec = {
  name: 'orders',
  describe: 'Manage orders',
  path: 'orders',
  style: 'v2-item',
  idLabel: 'order',
  ops: ['list', 'get', 'create', 'update', 'delete', 'delete-many'],
  fields: ORDER_FIELDS,
  params: ['status_id', 'customer_id', 'email', 'min_date_created', 'max_date_created', 'min_id', 'max_id', 'is_deleted', 'channel_id', 'sort'],
  actions: [
    {
      name: 'count',
      describe: 'Count orders by status',
      method: 'GET',
      path: 'v2/orders/count',
      envelope: false,
    },
    {
      name: 'status',
      describe: 'Get one order status by ID',
      method: 'GET',
      path: 'v2/order_statuses/{status_id}',
      args: ['status_id'],
      envelope: false,
    },
    {
      name: 'statuses',
      describe: 'List the store’s order statuses',
      method: 'GET',
      path: 'v2/order_statuses',
      envelope: false,
      fields: ['id', 'name', 'system_label', 'custom_label', 'order'],
    },
    {
      name: 'capture',
      describe: 'Capture an authorized payment',
      method: 'POST',
      path: `v3/${ORDER}/payment_actions/capture`,
      done: 'Payment captured',
    },
    {
      name: 'void',
      describe: 'Void an authorized payment',
      method: 'POST',
      path: `v3/${ORDER}/payment_actions/void`,
      done: 'Payment voided',
    },
    {
      name: 'refund-quote',
      describe: 'Quote a refund before issuing it',
      method: 'POST',
      path: `v3/${ORDER}/payment_actions/refund_quotes`,
      body: true,
    },
  ],
  children: [
    {
      name: 'products',
      describe: 'Line items on an order',
      path: `${ORDER}/products`,
      style: 'v2-item',
      ops: ['list', 'get'],
      idLabel: 'order product',
      fields: ['id', 'product_id', 'variant_id', 'sku', 'name', 'quantity', 'total_inc_tax'],
    },
    {
      name: 'coupons',
      describe: 'Coupons applied to an order',
      path: `${ORDER}/coupons`,
      style: 'v2-item',
      ops: ['list'],
      fields: ['id', 'coupon_id', 'code', 'amount', 'type', 'discount'],
    },
    {
      name: 'taxes',
      describe: 'Tax lines on an order',
      path: `${ORDER}/taxes`,
      style: 'v2-item',
      ops: ['list'],
      fields: ['id', 'order_address_id', 'tax_rate', 'name', 'class', 'line_amount'],
    },
    {
      name: 'messages',
      describe: 'Messages on an order',
      path: `${ORDER}/messages`,
      style: 'v2-item',
      ops: ['list'],
      fields: ['id', 'staff_id', 'customer_id', 'type', 'status', 'date_created'],
    },
    {
      name: 'shipping-addresses',
      describe: 'Shipping addresses on an order',
      path: `${ORDER}/shipping_addresses`,
      style: 'v2-item',
      ops: ['list', 'get', 'update'],
      idLabel: 'shipping address',
      fields: ['id', 'first_name', 'last_name', 'city', 'state', 'country', 'zip', 'shipping_method'],
      children: [
        {
          name: 'quotes',
          describe: 'Shipping quotes for an address',
          path: `${ORDER}/shipping_addresses/{shipping_address_id}/shipping_quotes`,
          style: 'v2-item',
          ops: ['list'],
        },
      ],
    },
    {
      name: 'shipments',
      describe: 'Shipments on an order',
      path: `${ORDER}/shipments`,
      style: 'v2-item',
      idLabel: 'shipment',
      ops: ['list', 'get', 'create', 'update', 'delete', 'delete-many'],
      fields: ['id', 'order_id', 'tracking_number', 'shipping_method', 'shipping_provider', 'date_created'],
      actions: [
        {
          name: 'count',
          describe: 'Count shipments on an order',
          method: 'GET',
          path: `v2/${ORDER}/shipments/count`,
          envelope: false,
        },
      ],
    },
    {
      name: 'consignments',
      describe: 'Consignments on an order',
      path: `${ORDER}/consignments`,
      style: 'v2-item',
      ops: ['list'],
      actions: [
        {
          name: 'quotes',
          describe: 'Shipping quotes for a shipping consignment',
          method: 'GET',
          path: `v2/${ORDER}/consignments/shipping/{shipping_consignment_id}/shipping_quotes`,
          envelope: false,
        },
      ],
    },
    {
      name: 'transactions',
      describe: 'Payment transactions on an order',
      path: `${ORDER}/transactions`,
      style: 'v3-item',
      ops: ['list'],
      fields: ['id', 'event', 'method', 'amount', 'currency', 'gateway', 'status', 'date_created'],
    },
    {
      name: 'refunds',
      describe: 'Refunds on an order',
      path: `${ORDER}/payment_actions/refunds`,
      style: 'v3-item',
      ops: ['list', 'create'],
      idLabel: 'refund',
      fields: ['id', 'order_id', 'total_amount', 'reason', 'created', 'user_id'],
    },
    {
      name: 'all-refunds',
      describe: 'Refunds across every order',
      path: 'orders/payment_actions/refunds',
      style: 'v3-item',
      ops: ['list', 'get'],
      idLabel: 'refund',
      fields: ['id', 'order_id', 'total_amount', 'reason', 'created'],
      params: ['order_id:in', 'id:in'],
      actions: [
        {
          name: 'quote',
          describe: 'Quote a refund without naming the order in the path',
          method: 'POST',
          path: 'v3/orders/payment_actions/refund_quotes',
          body: true,
        },
      ],
    },
    {
      name: 'pickups',
      describe: 'Order pickups',
      path: 'orders/pickups',
      style: 'v3-batch',
      idLabel: 'pickup',
      fields: ['id', 'order_id', 'pickup_method_id', 'status', 'pickup_method_display_name'],
      params: ['order_id:in', 'id:in'],
    },
    {
      name: 'settings',
      describe: 'Store-wide order settings',
      path: 'orders/settings',
      style: 'v3-singleton',
      children: [
        {
          name: 'channel',
          describe: 'Per-channel order settings',
          path: 'orders/settings/channels/{channel_id}',
          style: 'v3-singleton',
        },
      ],
    },
    metafields(ORDER),
  ],
};

export const PICKUP: ResourceSpec = {
  name: 'pickup',
  describe: 'In-store pickup',
  children: [
    {
      name: 'methods',
      describe: 'Pickup methods',
      path: 'pickup/methods',
      style: 'v3-batch',
      idLabel: 'pickup method',
      fields: ['id', 'location_id', 'display_name', 'collection_instructions', 'collection_time_description'],
      params: ['id:in', 'location_id:in'],
    },
    {
      name: 'options',
      describe: 'Pickup options available for a cart',
      path: 'pickup/options',
      style: 'v3-item',
      ops: ['create'],
      idLabel: 'pickup option search',
    },
  ],
};
